//
// CrawlResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CrawlResponse: Codable, JSONEncodable, Hashable {

    public var success: Bool?
    public var id: String?
    public var url: String?

    public init(success: Bool? = nil, id: String? = nil, url: String? = nil) {
        self.success = success
        self.id = id
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
        case id
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(success, forKey: .success)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(url, forKey: .url)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension CrawlResponse: Identifiable {}
