//
// CrawlStatusResponseObjDataInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CrawlStatusResponseObjDataInner: Codable, JSONEncodable, Hashable {

    public var markdown: String?
    /** Raw HTML content of the page if `includeRawHtml`  is true */
    public var rawHtml: String?
    /** List of links on the page if `includeLinks` is true */
    public var links: [String]?
    /** Screenshot of the page if `includeScreenshot` is true */
    public var screenshot: String?
    public var metadata: ScrapeResponseDataMetadata?

    public init(markdown: String? = nil, rawHtml: String? = nil, links: [String]? = nil, screenshot: String? = nil, metadata: ScrapeResponseDataMetadata? = nil) {
        self.markdown = markdown
        self.rawHtml = rawHtml
        self.links = links
        self.screenshot = screenshot
        self.metadata = metadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case markdown
        case rawHtml
        case links
        case screenshot
        case metadata
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(markdown, forKey: .markdown)
        try container.encodeIfPresent(rawHtml, forKey: .rawHtml)
        try container.encodeIfPresent(links, forKey: .links)
        try container.encodeIfPresent(screenshot, forKey: .screenshot)
        try container.encodeIfPresent(metadata, forKey: .metadata)
    }
}

