//
// MapResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MapResponse: Codable, JSONEncodable, Hashable {

    public var success: Bool?
    public var links: [String]?

    public init(success: Bool? = nil, links: [String]? = nil) {
        self.success = success
        self.links = links
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
        case links
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(success, forKey: .success)
        try container.encodeIfPresent(links, forKey: .links)
    }
}

