//
// ScrapeAndExtractFromUrlRequestExtract.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Extract object */
public struct ScrapeAndExtractFromUrlRequestExtract: Codable, JSONEncodable, Hashable {

    /** The schema to use for the extraction (Optional) */
    public var schema: AnyCodable?
    /** The system prompt to use for the extraction (Optional) */
    public var systemPrompt: String?
    /** The prompt to use for the extraction without a schema (Optional) */
    public var prompt: String?

    public init(schema: AnyCodable? = nil, systemPrompt: String? = nil, prompt: String? = nil) {
        self.schema = schema
        self.systemPrompt = systemPrompt
        self.prompt = prompt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case schema
        case systemPrompt
        case prompt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(schema, forKey: .schema)
        try container.encodeIfPresent(systemPrompt, forKey: .systemPrompt)
        try container.encodeIfPresent(prompt, forKey: .prompt)
    }
}

