//
// ScrapeAndExtractFromUrlRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ScrapeAndExtractFromUrlRequest: Codable, JSONEncodable, Hashable {

    public enum Formats: String, Codable, CaseIterable {
        case markdown = "markdown"
        case html = "html"
        case rawhtml = "rawHtml"
        case links = "links"
        case screenshot = "screenshot"
        case extract = "extract"
        case screenshotAtFullpage = "screenshot@fullPage"
    }
    /** The URL to scrape */
    public var url: String
    /** Formats to include in the output. */
    public var formats: [Formats]?
    /** Tags to include in the output. */
    public var includeTags: [String]?
    /** Tags to exclude from the output. */
    public var excludeTags: [String]?
    /** Headers to send with the request. Can be used to send cookies, user-agent, etc. */
    public var headers: AnyCodable?
    /** Specify a delay in milliseconds before fetching the content, allowing the page sufficient time to load. */
    public var waitFor: Int? = 0
    /** Timeout in milliseconds for the request */
    public var timeout: Int? = 30000
    public var extract: ScrapeAndExtractFromUrlRequestExtract?

    public init(url: String, formats: [Formats]? = nil, includeTags: [String]? = nil, excludeTags: [String]? = nil, headers: AnyCodable? = nil, waitFor: Int? = 0, timeout: Int? = 30000, extract: ScrapeAndExtractFromUrlRequestExtract? = nil) {
        self.url = url
        self.formats = formats
        self.includeTags = includeTags
        self.excludeTags = excludeTags
        self.headers = headers
        self.waitFor = waitFor
        self.timeout = timeout
        self.extract = extract
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case url
        case formats
        case includeTags
        case excludeTags
        case headers
        case waitFor
        case timeout
        case extract
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(url, forKey: .url)
        try container.encodeIfPresent(formats, forKey: .formats)
        try container.encodeIfPresent(includeTags, forKey: .includeTags)
        try container.encodeIfPresent(excludeTags, forKey: .excludeTags)
        try container.encodeIfPresent(headers, forKey: .headers)
        try container.encodeIfPresent(waitFor, forKey: .waitFor)
        try container.encodeIfPresent(timeout, forKey: .timeout)
        try container.encodeIfPresent(extract, forKey: .extract)
    }
}

